/**
 * The panel bridge protocol — what a panel iframe is allowed to ask for.
 *
 * A panel is extension-authored HTML in a sandboxed iframe with its own origin.
 * It cannot reach the app's DOM, its IPC, or the extension's own Node module;
 * everything it does it asks for over `postMessage`, and every request lands
 * here before anything acts on it.
 *
 * The renderer relays; MAIN decides. The renderer is not a security boundary —
 * it holds the open message and the panel's own frame, so a panel that could
 * talk it into an answer would have bypassed the permission model entirely.
 * Each request is forwarded to main, checked against the extension's granted
 * permissions there, and only then answered.
 */

import type { EmailRecord } from '../types/models';
import { hasTag, parseTags } from '../utils/tags';

import type { ExtensionPermission } from './types';

/** Request a panel can make of the host. */
export type PanelRequestMethod =
  /** The message the reader currently has open. Requires `email:read`. */
  | 'message.current'
  /** Read/write the extension's own storage. Requires `storage:local`. */
  | 'storage.get'
  | 'storage.set'
  | 'storage.delete'
  | 'storage.keys'
  /** Read the extension's settings. Requires `settings:read`. */
  | 'settings.get'
  | 'settings.all'
  /** Call a function the extension's module exported. */
  | 'exports.call'
  /** Raise a notification through the app's own UI. Requires `ui:notify`. */
  | 'ui.notify'
  /** Read one message by id. Requires `email:read`. */
  | 'mail.get'
  /** The folders of an account. Requires `email:read`. */
  | 'mail.folders'
  /** Flip read/starred. Requires `email:flag`. */
  | 'mail.markRead'
  | 'mail.markUnread'
  | 'mail.star'
  | 'mail.unstar'
  /** Add or remove a label. Requires `email:label`. */
  | 'mail.addLabel'
  | 'mail.removeLabel'
  /** Move to another folder. Requires `email:move`. */
  | 'mail.move'
  /** Move to trash — never an expunge. Requires `email:delete`. */
  | 'mail.trash'
  /** Ask the app to close this panel. Always allowed — it is the panel itself. */
  | 'panel.close'
  /** Ask for a different height, for a panel that sizes to its content. */
  | 'panel.resize';

/**
 * The permission each request needs, or null when it needs none.
 *
 * A single table rather than a check at each call site: a method added without
 * a decision here has no entry, and `panelRequestPermission` refuses it. The
 * default is deny, not allow.
 */
const PANEL_REQUEST_PERMISSIONS: Readonly<
  Record<PanelRequestMethod, ExtensionPermission | null>
> = {
  'message.current': 'email:read',
  'storage.get': 'storage:local',
  'storage.set': 'storage:local',
  'storage.delete': 'storage:local',
  'storage.keys': 'storage:local',
  // The same grant the extension's own code needs to read them. A panel is not
  // a way around a permission the extension was refused.
  'settings.get': 'settings:read',
  'settings.all': 'settings:read',
  // The module decides what it exposes; reaching it needs no extra grant,
  // because everything the module itself does is already permission-checked
  // where it happens.
  'exports.call': null,
  'ui.notify': 'ui:notify',
  // A panel reaches the same mail API the extension's own code does, under the
  // same grants. Listing each method rather than one 'mail.*' wildcard is the
  // point of the table: a new mail method has no entry until someone decides
  // which permission owns it, and until then the bridge refuses it.
  'mail.get': 'email:read',
  'mail.folders': 'email:read',
  'mail.markRead': 'email:flag',
  'mail.markUnread': 'email:flag',
  'mail.star': 'email:flag',
  'mail.unstar': 'email:flag',
  'mail.addLabel': 'email:label',
  'mail.removeLabel': 'email:label',
  'mail.move': 'email:move',
  'mail.trash': 'email:delete',
  'panel.close': null,
  'panel.resize': null,
};

/** Whether `method` is one the bridge knows at all. */
export function isPanelRequestMethod(value: unknown): value is PanelRequestMethod {
  return typeof value === 'string' && value in PANEL_REQUEST_PERMISSIONS;
}

/**
 * The permission `method` requires.
 *
 * Returns `undefined` for a method the bridge does not know — the caller must
 * treat that as a refusal, never as "no permission needed".
 */
export function panelRequestPermission(
  method: string
): ExtensionPermission | null | undefined {
  if (!isPanelRequestMethod(method)) return undefined;
  return PANEL_REQUEST_PERMISSIONS[method];
}

/** A request from a panel, as it arrives from the iframe. */
export interface PanelRequest {
  /** Correlates the reply. Generated by the panel; never trusted for anything else. */
  requestId: string;
  method: PanelRequestMethod;
  params?: unknown;
}

/** The host's answer to one request. */
export interface PanelResponse {
  requestId: string;
  ok: boolean;
  value?: unknown;
  error?: string;
}

/**
 * Validate an inbound `postMessage` payload as a panel request.
 *
 * Everything here arrives from extension-authored code, so the shape is checked
 * rather than assumed — an unknown method or a missing id is dropped, not
 * coerced into something the host will act on.
 */
export function parsePanelRequest(payload: unknown): PanelRequest | undefined {
  if (!payload || typeof payload !== 'object') return undefined;
  const candidate = payload as Record<string, unknown>;

  if (candidate.channel !== PANEL_BRIDGE_CHANNEL) return undefined;
  if (typeof candidate.requestId !== 'string' || !candidate.requestId) return undefined;
  if (!isPanelRequestMethod(candidate.method)) return undefined;

  return {
    requestId: candidate.requestId,
    method: candidate.method,
    params: candidate.params,
  };
}

/** Marks a `postMessage` payload as belonging to this bridge. */
export const PANEL_BRIDGE_CHANNEL = 'sarv-panel-bridge';

/** Host-initiated notifications a panel can listen for. */
export type PanelEventName = 'message-changed' | 'theme-changed';

/** A message pushed to a panel without it having asked. */
export interface PanelEvent {
  channel: typeof PANEL_BRIDGE_CHANNEL;
  event: PanelEventName;
  payload?: unknown;
}

/**
 * The shape of a message a panel is given.
 *
 * Deliberately a named subset rather than the stored row: `EmailRecord` grows
 * over time, and passing it straight through would silently hand panels every
 * field anyone ever adds to it — sync bookkeeping, spam verdicts, server state.
 * Anything a panel should see is added here, on purpose, once.
 *
 * Timestamps stay as the stored UTC epoch; the panel renders them in the
 * reader's own zone, the same as the rest of the app.
 */
export interface PanelMessage {
  id: string;
  threadId: string;
  folderId: string;
  subject: string;
  fromAddress: string;
  fromName?: string;
  toAddress: string;
  ccAddress?: string;
  /** UTC epoch SECONDS, as stored. The panel renders it in the reader's zone. */
  date: number;
  /** Every tag on the message: folders, flags and categories alike. */
  labels: string[];
  isRead: boolean;
  isStarred: boolean;
  hasAttachments: boolean;
  /** Plain-text body, empty until the body has been fetched. */
  body: string;
}

/** Reduce a stored message to what a panel is allowed to see. */
export function toPanelMessage(email: EmailRecord): PanelMessage {
  return {
    id: email.id,
    threadId: email.threadId,
    folderId: email.folderId,
    subject: email.subject ?? '',
    fromAddress: email.fromAddress ?? '',
    fromName: email.fromName ?? undefined,
    toAddress: email.toAddress ?? '',
    ccAddress: email.ccAddress ?? undefined,
    date: email.date,
    labels: parseTags(email.tags ?? ''),
    isRead: hasTag(email.tags ?? '', 'read'),
    isStarred: hasTag(email.tags ?? '', 'starred'),
    hasAttachments: Boolean(email.hasAttachments),
    body: email.cleanBody ?? '',
  };
}
