import { useState, useRef, useCallback, type MouseEvent as ReactMouseEvent } from 'react';

import { useClickAway } from '../hooks/useClickAway';
import { useEmailStore } from '../store/email-store';
import { editorHtmlToText } from '../utils/editor-text';
import { currentViewport, placeMenu, type MenuPlacement } from '../utils/menu-placement';
import { getSignatureHtml } from '../utils/signatures';

import { SELECTION_MENU_WIDTH } from './SelectionPolishMenu';

export interface AttachmentFile {
    name?: string;
    filename?: string;
    size: number;
    type: string;
    path?: string;
    content?: string;
    contentType?: string;
    encoding?: string;
}

export interface ComposeDraft {
    to?: string;
    cc?: string;
    bcc?: string;
    subject?: string;
    htmlContent?: string;
    attachments?: AttachmentFile[];
    replyToEmail?: any;
    mode?: 'new' | 'reply' | 'replyAll' | 'forward';
    isInline?: boolean;
    /** True when this draft was auto-generated by the Email Agent. */
    isAIDraft?: boolean;
    /** Reasoning the agent recorded for why it drafted this reply. */
    aiReasoning?: string;
    /** Agent decision row id — resolved when user sends or discards. */
    agentDecisionId?: string;
}

export interface UseComposeProps {
    initialDraft?: ComposeDraft;
}

export function useCompose({ initialDraft }: UseComposeProps) {
    const { sendEmail } = useEmailStore();

    const [to, setTo] = useState(initialDraft?.to || '');
    const [pendingTo, setPendingTo] = useState('');
    const [cc, setCc] = useState(initialDraft?.cc || '');
    const [pendingCc, setPendingCc] = useState('');
    const [bcc, setBcc] = useState(initialDraft?.bcc || '');
    const [pendingBcc, setPendingBcc] = useState('');
    const [subject, setSubject] = useState(initialDraft?.subject || '');

    const [htmlBody, setHtmlBody] = useState(initialDraft?.htmlContent || '');
    // Seeded from the draft: the editor only reports text on a keystroke, and
    // plainBody gates Send — '' here disabled Send on a reopened draft.
    const [plainBody, setPlainBody] = useState(() => editorHtmlToText(initialDraft?.htmlContent));
    const [attachments, setAttachments] = useState<AttachmentFile[]>(initialDraft?.attachments || []);

    const [sending, setSending] = useState(false);

    // Feature states
    const [showCc, setShowCc] = useState(!!initialDraft?.cc);
    const [showBcc, setShowBcc] = useState(!!initialDraft?.bcc);

    // AI Polish states
    const [showPolishModal, setShowPolishModal] = useState(false);
    const [polishMode, setPolishMode] = useState<'full' | 'selection'>('full');
    const [selectedText, setSelectedText] = useState('');

    // The right-click menu over a selection (SelectionPolishMenu): where it is
    // drawn, or null while it is closed.
    const [contextMenuPlacement, setContextMenuPlacement] = useState<MenuPlacement | null>(null);
    const contextMenuRef = useRef<HTMLDivElement>(null);
    const closeContextMenu = useCallback(() => setContextMenuPlacement(null), []);
    // Closes on a press anywhere else — including inside a framed body, which
    // the host document never hears about (useClickAway's window blur).
    useClickAway(contextMenuRef, contextMenuPlacement !== null, closeContextMenu);

    // Focus Editor utility
    const focusEditor = (selector: string) => {
        const editor = document.querySelector(`${selector} .ProseMirror, ${selector} [contenteditable="true"]`) as HTMLElement;
        if (editor) editor.focus();
    };

    /**
     * An editor's right-click. Over a selection, with an AI provider, it opens
     * the polish menu at the pointer — placed by `placeMenu`, so a right-click
     * near the window's right or bottom edge keeps the whole menu on-screen
     * (the pointer's raw coordinates drew it partly off). Anything else is
     * left to the browser: no `preventDefault`, no menu.
     */
    const handleSelectionContextMenu = (e: ReactMouseEvent, hasAIProvider: boolean) => {
        if (!hasAIProvider) return;
        const selected = window.getSelection()?.toString().trim() || '';
        if (!selected) return;
        e.preventDefault();
        setSelectedText(selected);
        setContextMenuPlacement(
            placeMenu({ kind: 'point', x: e.clientX, y: e.clientY }, currentViewport(), SELECTION_MENU_WIDTH),
        );
    };

    /** The menu's one item: polish the selection it was opened over. */
    const polishSelection = () => {
        setContextMenuPlacement(null);
        setPolishMode('selection');
        setShowPolishModal(true);
    };

    /** Replace the body programmatically (draft restore, AI rewrite), keeping
     *  the plain-text copy that gates Send in step with the HTML. */
    const setBody = (html: string) => {
        setHtmlBody(html);
        setPlainBody(editorHtmlToText(html));
    };

    const handleEditorChange = (html: string, text: string) => {
        setHtmlBody(html);
        setPlainBody(text);
    };

    const mergeEmails = (committed: string, pending: string) => {
        const rawCommitted = committed.split(',').map(e => e.trim()).filter(Boolean);
        const rawPending = pending.split(',').map(e => e.trim()).filter(e => e.includes('@'));
        return [...new Set([...rawCommitted, ...rawPending])];
    };

    const handleAttach = async () => {
        const result = await window.electronAPI.dialog.pickFiles();
        if (result.success && result.data?.length) {
            setAttachments(prev => [...prev, ...result.data as any]);
        }
    };

    const removeAttachment = (index: number) => {
        setAttachments(prev => prev.filter((_, i) => i !== index));
    };

    // Context-aware signature: 'new' uses the "for new emails" default,
    // 'reply' uses the "on reply/forward" default. Reads the multi-signature
    // model via the shared helper (with legacy-single-signature migration).
    const getSignature = (context: 'new' | 'reply' = 'new', accountId?: string): string => getSignatureHtml(context, accountId);

    return {
        // State values
        to, setTo, pendingTo, setPendingTo,
        cc, setCc, pendingCc, setPendingCc,
        bcc, setBcc, pendingBcc, setPendingBcc,
        subject, setSubject,
        htmlBody, setHtmlBody,
        plainBody, setPlainBody,
        setBody,
        attachments, setAttachments,
        sending, setSending,
        showCc, setShowCc,
        showBcc, setShowBcc,
        showPolishModal, setShowPolishModal,
        polishMode, setPolishMode,
        selectedText, setSelectedText,
        contextMenuPlacement,
        contextMenuRef,
        handleSelectionContextMenu,
        polishSelection,

        // Handlers
        handleEditorChange,
        mergeEmails,
        handleAttach,
        removeAttachment,
        getSignature,
        focusEditor,

        // Store
        sendEmail
    };
}
