import { useState, useRef, useEffect } from 'react';

import { useEmailStore } from '../store/email-store';
import { getSignatureHtml } from '../utils/signatures';

export interface AttachmentFile {
    name?: string;
    filename?: string;
    size: number;
    type: string;
    path?: string;
    content?: string;
    contentType?: string;
    encoding?: string;
}

export interface ComposeDraft {
    to?: string;
    cc?: string;
    bcc?: string;
    subject?: string;
    htmlContent?: string;
    attachments?: AttachmentFile[];
    replyToEmail?: any;
    mode?: 'new' | 'reply' | 'replyAll' | 'forward';
    isInline?: boolean;
    /** True when this draft was auto-generated by the Email Agent. */
    isAIDraft?: boolean;
    /** Reasoning the agent recorded for why it drafted this reply. */
    aiReasoning?: string;
    /** Agent decision row id — resolved when user sends or discards. */
    agentDecisionId?: string;
}

export interface UseComposeProps {
    initialDraft?: ComposeDraft;
}

export function useCompose({ initialDraft }: UseComposeProps) {
    const { sendEmail } = useEmailStore();

    const [to, setTo] = useState(initialDraft?.to || '');
    const [pendingTo, setPendingTo] = useState('');
    const [cc, setCc] = useState(initialDraft?.cc || '');
    const [pendingCc, setPendingCc] = useState('');
    const [bcc, setBcc] = useState(initialDraft?.bcc || '');
    const [pendingBcc, setPendingBcc] = useState('');
    const [subject, setSubject] = useState(initialDraft?.subject || '');

    const [htmlBody, setHtmlBody] = useState(initialDraft?.htmlContent || '');
    const [plainBody, setPlainBody] = useState('');
    const [attachments, setAttachments] = useState<AttachmentFile[]>(initialDraft?.attachments || []);

    const [sending, setSending] = useState(false);

    // Feature states
    const [showCc, setShowCc] = useState(!!initialDraft?.cc);
    const [showBcc, setShowBcc] = useState(!!initialDraft?.bcc);

    // AI Polish states
    const [showPolishModal, setShowPolishModal] = useState(false);
    const [polishMode, setPolishMode] = useState<'full' | 'selection'>('full');
    const [selectedText, setSelectedText] = useState('');

    // Context Menu state
    const [showContextMenu, setShowContextMenu] = useState(false);
    const [contextMenuPosition, setContextMenuPosition] = useState({ x: 0, y: 0 });
    const contextMenuRef = useRef<HTMLDivElement>(null);

    // Focus Editor utility
    const focusEditor = (selector: string) => {
        const editor = document.querySelector(`${selector} .ProseMirror, ${selector} [contenteditable="true"]`) as HTMLElement;
        if (editor) editor.focus();
    };

    // Close menus on click outside
    useEffect(() => {
        const handleClickOutside = (e: MouseEvent) => {
            if (contextMenuRef.current && !contextMenuRef.current.contains(e.target as Node)) {
                setShowContextMenu(false);
            }
        };
        document.addEventListener('mousedown', handleClickOutside);
        return () => document.removeEventListener('mousedown', handleClickOutside);
    }, []);

    const handleEditorChange = (html: string, text: string) => {
        setHtmlBody(html);
        setPlainBody(text);
    };

    const mergeEmails = (committed: string, pending: string) => {
        const rawCommitted = committed.split(',').map(e => e.trim()).filter(Boolean);
        const rawPending = pending.split(',').map(e => e.trim()).filter(e => e.includes('@'));
        return [...new Set([...rawCommitted, ...rawPending])];
    };

    const handleAttach = async () => {
        const result = await window.electronAPI.dialog.pickFiles();
        if (result.success && result.data?.length) {
            setAttachments(prev => [...prev, ...result.data as any]);
        }
    };

    const removeAttachment = (index: number) => {
        setAttachments(prev => prev.filter((_, i) => i !== index));
    };

    // Context-aware signature: 'new' uses the "for new emails" default,
    // 'reply' uses the "on reply/forward" default. Reads the multi-signature
    // model via the shared helper (with legacy-single-signature migration).
    const getSignature = (context: 'new' | 'reply' = 'new', accountId?: string): string => getSignatureHtml(context, accountId);

    return {
        // State values
        to, setTo, pendingTo, setPendingTo,
        cc, setCc, pendingCc, setPendingCc,
        bcc, setBcc, pendingBcc, setPendingBcc,
        subject, setSubject,
        htmlBody, setHtmlBody,
        plainBody, setPlainBody,
        attachments, setAttachments,
        sending, setSending,
        showCc, setShowCc,
        showBcc, setShowBcc,
        showPolishModal, setShowPolishModal,
        polishMode, setPolishMode,
        selectedText, setSelectedText,
        showContextMenu, setShowContextMenu,
        contextMenuPosition, setContextMenuPosition,
        contextMenuRef,

        // Handlers
        handleEditorChange,
        mergeEmails,
        handleAttach,
        removeAttachment,
        getSignature,
        focusEditor,

        // Store
        sendEmail
    };
}
